-- Durable, service-role-only LMIO persistence inside the approved Bayview
-- Supabase project. Browser clients receive no direct table access.

create table if not exists public.lmio_schema_versions (
  version integer primary key,
  applied_at timestamptz not null default now()
);

create table if not exists public.lmio_records (
  id bigint generated by default as identity primary key,
  kind text not null,
  symbol text,
  provider text,
  state text,
  payload jsonb not null default '{}'::jsonb,
  input_payload jsonb,
  result_payload jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists lmio_records_kind_id_idx
  on public.lmio_records (kind, id desc);
create index if not exists lmio_records_symbol_idx
  on public.lmio_records (symbol)
  where symbol is not null;

create table if not exists public.lmio_ingestion_dedup (
  fingerprint text primary key,
  record_type text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.lmio_news_events (
  fingerprint text primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.lmio_symbols (
  symbol text primary key,
  company text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.lmio_telegram_deliveries (
  dedupe_key text primary key,
  status text not null,
  payload jsonb not null,
  provider_message_id text,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_attempt_at timestamptz,
  created_at timestamptz not null default now()
);

insert into public.lmio_schema_versions(version)
values (6)
on conflict (version) do nothing;

alter table public.lmio_schema_versions enable row level security;
alter table public.lmio_records enable row level security;
alter table public.lmio_ingestion_dedup enable row level security;
alter table public.lmio_news_events enable row level security;
alter table public.lmio_symbols enable row level security;
alter table public.lmio_telegram_deliveries enable row level security;

revoke all on table public.lmio_schema_versions from anon, authenticated;
revoke all on table public.lmio_records from anon, authenticated;
revoke all on table public.lmio_ingestion_dedup from anon, authenticated;
revoke all on table public.lmio_news_events from anon, authenticated;
revoke all on table public.lmio_symbols from anon, authenticated;
revoke all on table public.lmio_telegram_deliveries from anon, authenticated;

grant all on table public.lmio_schema_versions to service_role;
grant all on table public.lmio_records to service_role;
grant all on table public.lmio_ingestion_dedup to service_role;
grant all on table public.lmio_news_events to service_role;
grant all on table public.lmio_symbols to service_role;
grant all on table public.lmio_telegram_deliveries to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.lmio_put_provider_snapshot(
  p_fingerprint text,
  p_provider text,
  p_symbol text,
  p_company text,
  p_observed_at text,
  p_payload jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.lmio_ingestion_dedup(fingerprint, record_type)
  values (p_fingerprint, 'provider_snapshot')
  on conflict (fingerprint) do nothing;
  if not found then
    return false;
  end if;

  insert into public.lmio_records(kind, provider, symbol, payload, metadata)
  values (
    'provider_snapshots',
    p_provider,
    upper(p_symbol),
    p_payload,
    jsonb_build_object('observed_at', p_observed_at)
  );

  insert into public.lmio_symbols(symbol, company, payload)
  values (
    upper(p_symbol),
    p_company,
    jsonb_build_object('source', p_payload -> 'source', 'observed_at', p_observed_at)
  )
  on conflict (symbol) do update
  set company = excluded.company,
      payload = excluded.payload,
      updated_at = now();
  return true;
end;
$$;

create or replace function public.lmio_put_ownership_event(
  p_fingerprint text,
  p_symbol text,
  p_event_type text,
  p_source_url text,
  p_payload jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.lmio_ingestion_dedup(fingerprint, record_type)
  values (p_fingerprint, 'ownership_event')
  on conflict (fingerprint) do nothing;
  if not found then
    return false;
  end if;

  insert into public.lmio_records(kind, symbol, payload, metadata)
  values (
    'ownership_events',
    upper(p_symbol),
    p_payload,
    jsonb_build_object('event_type', p_event_type, 'source_url', p_source_url)
  );
  return true;
end;
$$;

create or replace function public.lmio_upsert_telegram_delivery(
  p_dedupe_key text,
  p_status text,
  p_payload jsonb,
  p_provider_message_id text,
  p_attempt_increment integer
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.lmio_telegram_deliveries(
    dedupe_key,
    status,
    payload,
    provider_message_id,
    attempt_count,
    last_attempt_at
  )
  values (
    p_dedupe_key,
    p_status,
    p_payload,
    p_provider_message_id,
    greatest(p_attempt_increment, 0),
    case when p_attempt_increment > 0 then now() else null end
  )
  on conflict (dedupe_key) do update
  set status = excluded.status,
      payload = excluded.payload,
      provider_message_id = excluded.provider_message_id,
      attempt_count = (
        public.lmio_telegram_deliveries.attempt_count + excluded.attempt_count
      ),
      last_attempt_at = case
        when excluded.attempt_count > 0 then now()
        else public.lmio_telegram_deliveries.last_attempt_at
      end;
$$;

create or replace function public.lmio_runtime_counts()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'universe_runs', count(*) filter (where kind = 'universe_runs'),
    'screen_runs', count(*) filter (where kind = 'screen_runs'),
    'valuation_runs', count(*) filter (where kind = 'valuation_runs'),
    'news_events', (select count(*) from public.lmio_news_events),
    'reports', count(*) filter (where kind = 'reports'),
    'signal_outcomes', count(*) filter (where kind = 'signal_outcomes'),
    'telegram_deliveries', (select count(*) from public.lmio_telegram_deliveries),
    'system_events', count(*) filter (where kind = 'system_events'),
    'research_packs', count(*) filter (where kind = 'research_packs'),
    'conditional_plans', count(*) filter (where kind = 'conditional_plans'),
    'provider_health', count(*) filter (where kind = 'provider_health'),
    'symbols', (select count(*) from public.lmio_symbols),
    'provider_snapshots', count(*) filter (where kind = 'provider_snapshots'),
    'candidate_transitions', count(*) filter (where kind = 'candidate_transitions'),
    'trade_plan_transitions', count(*) filter (where kind = 'trade_plan_transitions'),
    'ownership_events', count(*) filter (where kind = 'ownership_events'),
    'signals', count(*) filter (where kind = 'signals'),
    'user_feedback', count(*) filter (where kind = 'user_feedback'),
    'strategy_performance', count(*) filter (where kind = 'strategy_performance'),
    'watchlists', count(*) filter (where kind = 'watchlists'),
    'watchlist_members', count(*) filter (where kind = 'watchlist_members')
  )
  from public.lmio_records;
$$;

revoke all on function public.lmio_put_provider_snapshot(
  text, text, text, text, text, jsonb
) from public, anon, authenticated;
revoke all on function public.lmio_put_ownership_event(
  text, text, text, text, jsonb
) from public, anon, authenticated;
revoke all on function public.lmio_upsert_telegram_delivery(
  text, text, jsonb, text, integer
) from public, anon, authenticated;
revoke all on function public.lmio_runtime_counts() from public, anon, authenticated;

grant execute on function public.lmio_put_provider_snapshot(
  text, text, text, text, text, jsonb
) to service_role;
grant execute on function public.lmio_put_ownership_event(
  text, text, text, text, jsonb
) to service_role;
grant execute on function public.lmio_upsert_telegram_delivery(
  text, text, jsonb, text, integer
) to service_role;
grant execute on function public.lmio_runtime_counts() to service_role;
