-- Physically isolate synthetic and test evidence from every operational LMIO table.
-- This table is service-role-only and is never queried by operational latest endpoints.

create table if not exists public.lmio_synthetic_records (
  id bigint generated by default as identity primary key,
  record_type text not null,
  provenance text not null check (provenance in ('synthetic_replay', 'test_fixture')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.lmio_schema_versions(version)
values (7)
on conflict (version) do nothing;

alter table public.lmio_synthetic_records enable row level security;
revoke all on table public.lmio_synthetic_records from anon, authenticated;
grant all on table public.lmio_synthetic_records to service_role;
grant usage, select on all sequences in schema public to service_role;
