"""Explicitly synthetic replay data for local demonstrations and tests."""

from datetime import UTC, datetime

from lmio.domain import DataProvenance, SecuritySnapshot, ValuationInput


def demo_universe() -> list[SecuritySnapshot]:
    observed = datetime(2026, 7, 30, tzinfo=UTC)
    rows = [
        (
            "META",
            "Meta Platforms",
            510,
            1300000,
            8000,
            22,
            28,
            82,
            40,
            29,
            0.35,
            24,
            31,
            18,
            8,
            8,
            1.5,
            80,
        ),
        (
            "MSFT",
            "Microsoft",
            495,
            3700000,
            9000,
            16,
            19,
            69,
            45,
            25,
            0.4,
            30,
            24,
            10,
            6,
            4,
            1.2,
            75,
        ),
        (
            "NVDA",
            "NVIDIA",
            180,
            4400000,
            15000,
            45,
            55,
            75,
            55,
            50,
            0.25,
            38,
            60,
            25,
            12,
            15,
            2.0,
            90,
        ),
        (
            "COST",
            "Costco",
            1010,
            450000,
            1200,
            9,
            11,
            13,
            4,
            18,
            0.5,
            3,
            20,
            15,
            3,
            2,
            1.1,
            65,
        ),
        (
            "SYN1",
            "Synthetic Quality One",
            80,
            15000,
            80,
            18,
            20,
            55,
            18,
            20,
            0.4,
            14,
            15,
            8,
            5,
            3,
            1.3,
            70,
        ),
        (
            "SYN2",
            "Synthetic Revision Two",
            42,
            6000,
            25,
            5,
            8,
            40,
            8,
            11,
            0.8,
            7,
            12,
            7,
            9,
            5,
            2.1,
            60,
        ),
        (
            "ILLIQ",
            "Synthetic Illiquid",
            1.5,
            100,
            0.2,
            50,
            50,
            60,
            20,
            20,
            0.2,
            15,
            30,
            20,
            10,
            4,
            2,
            80,
        ),
    ]
    return [
        SecuritySnapshot(
            symbol=symbol,
            company=company,
            observed_at=observed,
            source="LMIO synthetic replay fixture",
            provenance=DataProvenance.SYNTHETIC_REPLAY,
            price=price,
            market_cap_m=market_cap,
            average_dollar_volume_m=liquidity,
            revenue_growth_pct=revenue,
            eps_growth_pct=eps,
            gross_margin_pct=gross,
            operating_margin_pct=operating,
            roic_pct=roic,
            debt_to_equity=debt,
            fcf_margin_pct=fcf,
            relative_strength_6m=rs,
            price_above_200d_pct=above,
            earnings_revision_30d_pct=revision,
            earnings_surprise_pct=surprise,
            relative_volume=rel_volume,
            sector_strength=sector,
        )
        for (
            symbol,
            company,
            price,
            market_cap,
            liquidity,
            revenue,
            eps,
            gross,
            operating,
            roic,
            debt,
            fcf,
            rs,
            above,
            revision,
            surprise,
            rel_volume,
            sector,
        ) in rows
    ]


def meta_acceptance_input() -> ValuationInput:
    """Synthetic, non-current META-shaped case testing high growth CapEx divergence."""

    return ValuationInput(
        symbol="META",
        provenance=DataProvenance.SYNTHETIC_REPLAY,
        operating_cash_flow=100_000,
        capex=70_000,
        maintenance_capex=25_000,
        growth_capex=45_000,
        sustainable_owner_earnings=72_000,
        revenue=200_000,
        ebitda=80_000,
        net_income=65_000,
        ev_revenue_multiple=7,
        ev_ebitda_multiple=18,
        pe_multiple=24,
        p_fcf_multiple=28,
        net_cash=35_000,
        diluted_shares=2_500,
        growth_rate=0.12,
        terminal_growth=0.03,
        discount_rate=0.09,
        forecast_years=5,
        market_price=510,
        source="LMIO synthetic META acceptance fixture; not current market data",
        observed_at=datetime(2026, 7, 30, tzinfo=UTC),
        confidence=0.75,
    )
